/* FUNCTIONS */

select sign(-1), sing(5) from dual;
RESULTS: -1, 1

select round(4.756), trunc(4.756) from dual;
RESULTS 5, 4

SELECT SOUNDEX('Worthingtion'), SOUNDEX('Worthen') FROM DUAL;
RESULTS: W635, W635

SELECT ROUND(12.355143,2), ROUND(259.99,-1) FROM DUAL
RESULTS 12.36, 260

SELECT TRUNC(12.355143,2), TRUNC(259.99,-1) FROM DUAL
RESULTS 12.35, 250

/* TRUNCATING, ROUNDING TO THE NEAREST TENS IF i IS NEGATIVE */

SELECT REMAINDER(9,3), REMAINDER(10,3), REMAINDER(11,3) FROM DUAL;
RESULTS 0, 1, -1

SELECT MOD(9,3), MOD(10,3), MOD(11,3) FROM DUAL;
RESULTS 0, 1, 2

SELECT STATE, DECODE(STATE, 'CA', 'California',
							'IL', 'Illinois',
							'Other') AS DECODE_STATE
  FROM ADDRESSES;

RESULTS:
STATE		DECODED_STATE
NULL		OTHER
CA			California
TX			OTHER
IL			Illinois
QC			OTHER

SELECT NULLIF(1,2), NULLIF(1,1) FROM DUAL;
RESULTS: 1, NULL

SELECT NULLIF(NULL,NULL) FROM DUAL;
RESULTS: Syntax Error - NULLIF is doing Expression1 = Expression2, NULL = NULL is not a valid comparison


SELECT TO_CHAR(SYSDATE, 'DD-MON-RRRR HH:MM:SS') "Today's Date And Time" FROM DUAL;
Above query is syntactically correcy but format for mintues should be MI currently for minutes it will show MONTHS

SELECT TO_DSINTERVAL('40 08:30:00.03225') EVENT_TIME FROM DUAL;
RESULTS: 40 8:30:0.032250000

SELECT TO_YMINTERVAL('04-06') EVENT_TIME FROM DUAL;
RESULTS: 4-6
  
  
  

