/* CHECK FOR VIEW THAT STATE IS INVALID */
  SELECT STATUS, OBJECT_TYPE, OBJECT_NAME
    FROM USER_OBJECTS
   WHERE STATUS = 'INVALID'
ORDER BY OBJECT_NAME;

/* CHECK CONSTRAINTS ON A TABLE */
  SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE,
  	  	 R_CONSTRAINT_NAME, STATUS
  	FROM USER_CONSTRAINTS
   WHERE TABLE_NAME = 'CRUISES';
   