/* COUNT */
CREATE TABLE TEST_COUNT (
	test_colA VARCHAR2(20),
	test_colB VARCHAR2(20)
);

INSERT INTO TEST_COUNT VALUES(NULL,NULL);
INSERT INTO TEST_COUNT VALUES(1,1);

SELECT COUNT(*) FROM TEST_COUNT;
RESULTS: 2

TRUNCATE TABLE TEST_COUNT;
SELECT COUNT(*) FROM TEST_COUNT;
RESULTS: 0

/* RANK WITHIN GROUP */
CREATE TABLE TEST_RANK (
	test_colA VARCHAR2(20),
	test_colB VARCHAR2(20)
);

INSERT INTO TEST_RANK VALUES(1,1);
INSERT INTO TEST_RANK VALUES(2,2);
INSERT INTO TEST_RANK VALUES(3,3);
INSERT INTO TEST_RANK VALUES(4,4);

SELECT RANK(3) WITHIN GROUP (ORDER BY test_colB) FROM TEST_RANK;
RESULTS: 3

/* FIRST, LAST */
SELECT MAX(SQ_FT) KEEP (DENSE_RANK FIRST ORDER BY GUESTS) AS "Largest"
  FROM SHIP_CABINS;
RESULTS: 225
Description: Display the highest number of square feet for any and all cabins that accommodate the lowest number of guests according to the guests column.

